[project]
name = "franken-jet-notification-bot"
version = "0.1.0"
description = "FrankenJet Notification Bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiogram>=3.24.0",
    "faststream[rabbit]>=0.6.5",
    "pydantic-settings>=2.12.0",
]
